name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      # Build client
      - name: Build client
        working-directory: ./client
        run: |
          npm ci
          npm run build

      # Build server
      - name: Build server
        working-directory: ./server
        run: |
          npm ci
          npm run build

      # Run tests
      - name: Run tests
        working-directory: ./server
        run: npm run test
